# fly.toml app configuration file generated for mille-bornes-online on 2026-05-18T12:30:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mille-bornes-online'
primary_region = 'cdg'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
